/// Generated by AssetsRefGenerator on 2021/07/09
class Res {
  static const String facebook = "assets/images/facebook.png";
  static const String filter = "assets/images/filter.svg";
  static const String home = "assets/images/home.png";
  static const String icon = "assets/images/icon.png";
  static const String instagram = "assets/images/instagram.png";
  static const String ksa = "assets/images/ksa.png";
  static const String logo = "assets/images/logo.png";
  static const String logoCheck = "assets/images/logoCheck.png";
  static const String logoMark = "assets/images/logoMark.png";
  static const String marker = "assets/images/marker.png";
  static const String more = "assets/images/more.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String profile = "assets/images/profile.png";
  static const String reservation = "assets/images/reservation.png";
  static const String search = "assets/images/search.svg";
  static const String splash = "assets/images/splash.png";
  static const String telegram = "assets/images/telegram.png";
  static const String twitter = "assets/images/twitter.png";
  static const String usa = "assets/images/usa.png";
  static const String ar = "assets/lang/ar.json";
  static const String en = "assets/lang/en.json";
}
