/// Generated by AssetsRefGenerator on 2021/06/21
class Res {
  static const String filter = "assets/images/filter.svg";
  static const String home = "assets/images/home.png";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoCheck = "assets/images/logoCheck.png";
  static const String more = "assets/images/more.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String profile = "assets/images/profile.png";
  static const String reservation = "assets/images/reservation.png";
  static const String search = "assets/images/search.svg";
  static const String splash = "assets/images/splash.png";
  static const String ar = "assets/lang/ar.json";
  static const String en = "assets/lang/en.json";
}
